version: '3.4'

services:
 
  ms-deno:
    image: ms-deno
    container_name: ms-deno
    ports:
      - "9000:5000"    
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        PORT: 5000
    environment:
      ENV: production
